struct WeaponEntry
{
  unsigned int id;
  unsigned int chance;
};

enum Weapon : int
{
  None,
  Bazooka,
  HomingMissile,
  Mortar,
  HomingPigeon,
  SheepLauncher,
  Grenade,
  ClusterBomb,
  BananaBomb,
  Axe,
  EarthQuake,
  Shotgun,
  Handgun,
  Uzi,
  Minigun,
  Longbow,
  FirePunch,
  DragonBall,
  Kamikaze,
  SuicideBomber,
  Prod,
  Dynamite,
  Mine,
  Sheep,
  SuperSheep,
  AquaSheep,
  MoleBomb,
  AirStrike,
  NapalmStrike,
  PostalStrike,
  MineStrike,
  MoleSquadron,
  BlowTorch,
  PneumaticDrill,
  Girder,
  BaseballBat,
  BridgeKit,
  Batrope,
  Bungee,
  Parachute,
  Teleport,
  Scales,
  SuperBananaBomb,
  HolyHandGrenade,
  FlameThrower,
  SallyArmy,
  MBBomb,
  PetrolBomb,
  Skunk,
  MingVase,
  SheepStrike,
  CarpetBomb,
  MadCow,
  OldWoman,
  Donkey,
  NuclearBomb,
  Armageddon,
  INVALID1,
  INVALID2,
  SelectWorm,
  Freeze,
  MagicBullet,
  JetPack,
  LowGravity,
  FastWalk,
  LaserSight,
  Invisibility,
  DamageX2,
  CrateSpy,
  DoubleTime,
  CrateShower,
  INVALID3
};

static unsigned int szCustomChances = 10;

static WeaponEntry CustomChances[10] =
{ { Weapon::Dynamite, 1 },
{ Weapon::SuperSheep, 1 },
{ Weapon::EarthQuake, 1 },
{ Weapon::NuclearBomb,1 },
{ Weapon::PostalStrike,1 },
{ Weapon::Donkey,1 },
{ Weapon::HolyHandGrenade,1 },
{ Weapon::None,9 },
{ Weapon::SheepStrike,1 },
{ Weapon::Armageddon,1 } };

static const char* WeaponStrings[72] =
{
  "None",
  "Bazooka",
  "HomingMissile",
  "Mortar",
  "HomingPigeon",
  "SheepLauncher",
  "Grenade",
  "ClusterBomb",
  "BananaBomb",
  "Axe",
  "EarthQuake",
  "Shotgun",
  "Handgun",
  "Uzi",
  "Minigun",
  "Longbow",
  "FirePunch",
  "DragonBall",
  "Kamikaze",
  "SuicideBomber",
  "Prod",
  "Dynamite",
  "Mine",
  "Sheep",
  "SuperSheep",
  "AquaSheep",
  "MoleBomb",
  "AirStrike",
  "NapalmStrike",
  "PostalStrike",
  "MineStrike",
  "MoleSquadron",
  "BlowTorch",
  "PneumaticDrill",
  "Girder",
  "BaseballBat",
  "BridgeKit",
  "Batrope",
  "Bungee",
  "Parachute",
  "Teleport",
  "Scales",
  "SuperBananaBomb",
  "HolyHandGrenade",
  "FlameThrower",
  "SallyArmy",
  "MBBomb",
  "PetrolBomb",
  "Skunk",
  "MingVase",
  "SheepStrike",
  "CarpetBomb",
  "MadCow",
  "OldWoman",
  "Donkey",
  "NuclearBomb",
  "Armageddon",
  "INVALID1",
  "INVALID2",
  "SelectWorm",
  "Freeze",
  "MagicBullet",
  "JetPack",
  "LowGravity",
  "FastWalk",
  "LaserSight",
  "Invisibility",
  "DamageX2",
  "CrateSpy",
  "DoubleTime",
  "CrateShower",
  "INVALID3"
};